### ISSUE TITLE
Ansible wants to write to /.ansible/tmp

### ISSUE THREAD

**Issue by abellotti** [abellotti/discovery-deployer#2]
See the workaround https://github.com/abellotti/discovery-deployer/blob/master/discovery_template.yaml#L157:

```
            volumeMounts:
            - mountPath: /var/data
              name: discovery-data-volume-claim
            - mountPath: /var/log
              name: discovery-log-volume-claim
            - mountPath: /.ansible
              name: discovery-data-volume-claim
            ...
```
🤮 

Essentially mounting our writable /var/data PV there.

We should be able to tell Ansible, hey write over there: `/var/data/tmp`

Something about defining a remote temp:

See:
- https://devops.stackexchange.com/questions/10703/ansible-temp-dir-change
- https://docs.ansible.com/ansible/latest/collections/ansible/builtin/sh_shell.html

Maybe just defining ANSIBLE_REMOTE_TMP=/tmp but have it ENV configurable so the OCP template can declare as needed. (i.e. /var/data/tmp)
